import Foundation
import Observation

/// Runtime localization manager — provides English/Spanish translations without
/// requiring .strings files or an app restart. Views access it via
/// @Environment(LocalizationManager.self). Changing `language` immediately
/// re-renders any view that called `localized(_:)` because @Observable tracks
/// the `language` property read inside the function.
@Observable
final class LocalizationManager {

    private(set) var language: String

    init() {
        language = UserDefaults.standard.string(forKey: "scanart.language") ?? "en"
    }

    func setLanguage(_ lang: String) {
        language = lang
        UserDefaults.standard.set(lang, forKey: "scanart.language")
        UserDefaults.standard.set([lang], forKey: "AppleLanguages")
        UserDefaults.standard.synchronize()
    }

    func callAsFunction(_ key: String) -> String { localized(key) }

    func localized(_ key: String) -> String {
        let table = language.hasPrefix("es") ? Self.spanish : Self.english
        return table[key] ?? key
    }

    // MARK: - English

    // swiftlint:disable file_length
    private static let english: [String: String] = [
        // ── Navigation / common ──────────────────────────────────────────────
        "app.name":                         "Scan Art",
        "nav.settings":                     "Settings",
        "nav.help":                         "Help",
        "nav.about":                        "About",
        "nav.remoteControl":                "Remote Control",
        "action.cancel":                    "Cancel",
        "action.save":                      "Save",
        "action.saving":                    "Saving…",
        "action.send":                      "Send",
        "action.stop":                      "Stop",
        "action.create":                    "Create",
        "action.done":                      "Done",
        "action.use":                       "Use",
        "action.disconnect":                "Disconnect",
        "action.reset":                     "Reset",
        "action.calculate":                 "Calculate",
        "action.delete":                    "Delete",
        // ── Home ─────────────────────────────────────────────────────────────
        "home.newProject":                  "New Project",
        "home.allProjects":                 "All Projects",
        "home.noProjectsYet":              "No projects yet",
        "home.noProjectsSubtitle":         "Tap New Project to start measuring\nplaster thickness with LiDAR.",
        "home.recentProjects":             "RECENT PROJECTS",
        "home.scans":                       "scans",
        // ── Settings ─────────────────────────────────────────────────────────
        "settings.title":                   "Settings",
        "settings.defaults":                "Defaults",
        "settings.defaultUnit":             "Default Unit",
        "settings.defaultUnitNote":         "Used to pre-fill new projects. Each project can still use its own unit.",
        "settings.language":                "Language",
        "settings.language.en":             "English",
        "settings.language.es":             "Español",
        "settings.language.note":           "Language changes apply immediately.",
        "settings.storage":                 "Storage",
        "settings.availableSpace":          "Available Space",
        "settings.storageNote":             "Scan Art stores all projects, scans, and reports locally on this device — nothing is uploaded.",
        "settings.version":                 "Version",
        // ── Project form (Create + Edit) ─────────────────────────────────────
        "project.new":                      "New Project",
        "project.edit":                     "Edit Project",
        "project.photo":                    "Project Photo",
        "project.addPhoto":                 "Add Photo",
        "project.removePhoto":              "Remove Photo",
        "project.section":                  "Project",
        "project.name":                     "Project name *",
        "project.customer":                 "Customer name",
        "project.engineer":                 "Engineer name",
        "project.location":                 "Location",
        "project.site":                     "Site",
        "project.building":                 "Building",
        "project.room":                     "Room",
        "project.floor":                    "Floor number",
        "project.notes":                    "Notes",
        "project.workType":                 "Work Type",
        "project.unit":                     "Unit",
        "project.targetThickness":          "Target thickness",
        "project.tolerance":                "Tolerance (±)",
        "project.recommended":              "Recommended:",
        "project.deleteTitle":              "Delete Project",
        "project.deleteConfirm":            "Delete this project? This removes all scans and reports.",
        "project.deleteScansAndSave":       "Delete Scans & Save",
        "project.deleteScansTitle":         "Delete all scan data?",
        "project.deleteScansMessage":       "Saving will permanently delete all original scans, rescans, and thickness analysis results for this project.",
        "project.deleteScansWarning":       "Saving will permanently delete %d scan(s) and all thickness results.",
        // ── Project list ─────────────────────────────────────────────────────
        "projects.title":                   "Projects",
        "projects.search":                  "Search by name, customer, site, engineer",
        "projects.empty":                   "No projects yet",
        "projects.emptySearch":             "No matching projects",
        // ── Project detail ────────────────────────────────────────────────────
        "detail.startOriginalScan":         "Start Original Scan",
        "detail.newRescan":                 "New Rescan",
        "detail.reports":                   "Reports",
        "detail.colorPalette":              "Color Palette",
        "detail.colorPalette.custom":       "Custom",
        "detail.timeline":                  "TIMELINE",
        "detail.desired":                   "Desired",
        "detail.tolerance":                 "Tolerance",
        "detail.tapToAnalyze":             "Tap to analyze",
        "detail.vertices":                  "vertices",
        "detail.coverage":                  "coverage",
        // ── Color palette editor ──────────────────────────────────────────────
        "palette.title":                    "Color Palette",
        "palette.preview":                  "GRADIENT PREVIEW",
        "palette.resetToDefault":           "Reset to Default",
        "palette.bands":                    "bands",
        // ── Reports ───────────────────────────────────────────────────────────
        "reports.title":                    "Reports",
        "reports.empty":                    "No reports yet",
        "reports.emptyNote":                "Generate one from the Analysis screen after computing a thickness map.",
        // ── Scan ──────────────────────────────────────────────────────────────
        "scan.finish":                      "Finish Scan",
        "scan.save":                        "Save Scan",
        "scan.label.optional":              "Label (optional)",
        "scan.label.placeholder":           "e.g. Original Scan",
        "scan.mesh":                        "Mesh",
        "scan.anchors":                     "anchors",
        "scan.coverage":                    "Coverage",
        "scan.tracking.initializing":       "Move the device slowly to begin tracking…",
        "scan.tracking.excessiveMotion":    "Moving too fast — slow down.",
        "scan.tracking.insufficientFeatures": "Point at a more textured surface.",
        "scan.tracking.relocalizing":       "Finding your position…",
        "scan.tracking.limited":            "Tracking is limited.",
        // ── Rescan ────────────────────────────────────────────────────────────
        "rescan.finish":                    "Finish Rescan",
        "rescan.save":                      "Save Rescan",
        "rescan.label.placeholder":         "e.g. After Second Coat",
        "rescan.colors":                    "Colors",
        "rescan.colors.active":             "Active",
        "rescan.colors.ready":              "Ready",
        "rescan.colors.loading":            "Loading",
        "rescan.heatmap":                   "Heatmap",
        "rescan.heatmapActive":             "Heatmap Active",
        "rescan.cubicMeters":               "Cubic Meters",
        "rescan.calculating":               "Calculating…",
        "rescan.loadingMesh":               "Loading mesh…",
        "rescan.volume.plaster":            "Plaster Vol.",
        "rescan.volume.excavation":         "Excav. Vol.",
        // ── Analysis ──────────────────────────────────────────────────────────
        "analysis.title":                   "Analysis",
        "analysis.generateThicknessMap":    "Generate Thickness Map",
        "analysis.thicknessMapNotGenerated": "Thickness map not generated yet",
        "analysis.computing":               "Computing…",
        "analysis.fullStatistics":          "Full Statistics",
        // ── Remote Control ────────────────────────────────────────────────────
        "remote.broadcasting":              "Broadcasting",
        "remote.starting":                  "Starting…",
        "remote.joinRoom":                  "Join Room",
        "remote.broadcastScreen":           "Broadcast Screen",
        "remote.joinARoom":                 "Join a Room",
        "remote.stopBroadcasting":          "Stop Broadcasting",
        "remote.stopBroadcastingQ":         "Stop Broadcasting?",
        "remote.title":                     "Remote Control",
        "remote.peerToPeerTitle":           "Peer-to-Peer Screen Control",
        "remote.peerToPeerSubtitle":        "Share your screen and let another device control it — over WiFi or Bluetooth, no internet required.",
        "remote.waitingForController":      "Waiting for controller…",
        "remote.connectedControllers":      "CONNECTED CONTROLLERS",
        "remote.waitingForDevice":          "Waiting for a device to join…",
        "remote.useAppFreely":              "Use the app freely",
        "remote.useAppFreelySubtitle":      "Navigate anywhere — the controller sees whatever screen you're on and can tap to control it. A broadcasting indicator stays visible at the bottom of every screen.",
        "remote.from":                      "From:",
        "remote.connectedTo":               "Connected",
        "remote.searchingBroadcasters":     "Searching for broadcasters…",
        "remote.noBroadcastersFound":       "No broadcasters found",
        "remote.noBroadcastersNote":        "Open Scan Art on the other device, tap Remote Control → Broadcast Screen, then return here.",
        "remote.availableRooms":            "AVAILABLE ROOMS",
        "remote.broadcasting.tapToConnect": "Broadcasting · tap to connect",
        "remote.waitingForStream":          "Waiting for screen stream…",
        "remote.keyboard":                  "Type & Send",
        "remote.keyboard.prompt":           "Type text to send to the broadcaster",
        "remote.keyboard.placeholder":      "Enter text…",
        "remote.info.broadcastScreen.title": "Broadcast Screen",
        "remote.info.broadcastScreen.body": "Streams your screen to a controller. Navigate the app normally — the controller sees everything you do.",
        "remote.info.joinRoom.title":       "Join a Room",
        "remote.info.joinRoom.body":        "Connects to a broadcaster, shows their live screen, and sends your taps back to control it.",
        "remote.info.wifi.title":           "WiFi or Bluetooth",
        "remote.info.wifi.body":            "Both devices must be nearby. Works on the same local network or direct Bluetooth — no cloud.",
        // ── Help ─────────────────────────────────────────────────────────────
        "help.title":                       "Help",
        "help.1.title":                     "1. Create a Project",
        "help.1.text":                      "Set the desired plaster thickness and tolerance for the wall you're measuring. This drives the color legend and pass/fail statistics.",
        "help.2.title":                     "2. Original Scan",
        "help.2.text":                      "Before plastering, scan the bare wall. Move slowly and cover the whole area, including a bit of floor, ceiling, or a doorway if visible — these help align future rescans.",
        "help.3.title":                     "3. Rescan After Plastering",
        "help.3.text":                      "Once plaster is applied, start a rescan. Scan Art will try to relocalize to the exact position of the original scan — pan slowly around the room until alignment succeeds.",
        "help.4.title":                     "4. Generate Thickness Map",
        "help.4.text":                      "In Analysis, tap Generate Thickness Map. Scan Art compares both scans and colors the wall by how much thicker it grew — green means on target.",
        "help.5.title":                     "5. Export & Report",
        "help.5.text":                      "Export the colored mesh to DXF, OBJ, PLY, STL, USDZ, CSV, or JSON, or generate a PDF report to share with your client or team.",
        "help.tips.title":                  "Tips for Best Results",
        "help.tips.text":                   "Scan in good, even lighting. Avoid scanning highly reflective or completely blank surfaces. Keep the device moving slowly and steadily — quick motions can lose tracking.",
        // ── About ────────────────────────────────────────────────────────────
        "about.title":                      "About",
        "about.subtitle":                   "LiDAR-based plaster thickness measurement for civil engineers, architects, and contractors. Every scan, measurement, and report stays on this device — Scan Art works entirely offline.",
        "about.alignment":                  "Alignment",
        "about.alignment.value":            "ARKit world-map relocalization + ICP refinement",
        "about.measurement":                "Measurement",
        "about.measurement.value":          "Ray-mesh intersection thickness sampling",
        "about.storage":                    "Storage",
        "about.storage.value":              "100% on-device, no account or cloud required",
        // ── Splash ───────────────────────────────────────────────────────────
        "splash.tagline":                   "LiDAR Plaster Thickness Measurement",
        "splash.unsupported":               "This device is not supported.",
        "splash.unsupportedNote":           "Scan Art requires a LiDAR Scanner, available on iPhone Pro and iPad Pro models.",
        // ── Generate PDF ─────────────────────────────────────────────────────
        "export.generatePDF":               "Generate PDF Report",
    ]

    // MARK: - Spanish

    private static let spanish: [String: String] = [
        // ── Navigation / common ──────────────────────────────────────────────
        "app.name":                         "Scan Art",
        "nav.settings":                     "Configuración",
        "nav.help":                         "Ayuda",
        "nav.about":                        "Acerca de",
        "nav.remoteControl":                "Control Remoto",
        "action.cancel":                    "Cancelar",
        "action.save":                      "Guardar",
        "action.saving":                    "Guardando…",
        "action.send":                      "Enviar",
        "action.stop":                      "Detener",
        "action.create":                    "Crear",
        "action.done":                      "Listo",
        "action.use":                       "Usar",
        "action.disconnect":                "Desconectar",
        "action.reset":                     "Reiniciar",
        "action.calculate":                 "Calcular",
        "action.delete":                    "Eliminar",
        // ── Home ─────────────────────────────────────────────────────────────
        "home.newProject":                  "Nuevo Proyecto",
        "home.allProjects":                 "Todos los Proyectos",
        "home.noProjectsYet":              "Sin proyectos aún",
        "home.noProjectsSubtitle":         "Toca Nuevo Proyecto para comenzar a medir\nel espesor del revoque con LiDAR.",
        "home.recentProjects":             "PROYECTOS RECIENTES",
        "home.scans":                       "escaneos",
        // ── Settings ─────────────────────────────────────────────────────────
        "settings.title":                   "Configuración",
        "settings.defaults":                "Predeterminados",
        "settings.defaultUnit":             "Unidad predeterminada",
        "settings.defaultUnitNote":         "Se usa para completar nuevos proyectos. Cada proyecto puede usar su propia unidad.",
        "settings.language":                "Idioma",
        "settings.language.en":             "English",
        "settings.language.es":             "Español",
        "settings.language.note":           "Los cambios de idioma se aplican de inmediato.",
        "settings.storage":                 "Almacenamiento",
        "settings.availableSpace":          "Espacio disponible",
        "settings.storageNote":             "Scan Art guarda todos los proyectos, escaneos e informes localmente en este dispositivo — no se sube nada.",
        "settings.version":                 "Versión",
        // ── Project form ─────────────────────────────────────────────────────
        "project.new":                      "Nuevo Proyecto",
        "project.edit":                     "Editar Proyecto",
        "project.photo":                    "Foto del Proyecto",
        "project.addPhoto":                 "Agregar Foto",
        "project.removePhoto":              "Eliminar Foto",
        "project.section":                  "Proyecto",
        "project.name":                     "Nombre del proyecto *",
        "project.customer":                 "Nombre del cliente",
        "project.engineer":                 "Nombre del ingeniero",
        "project.location":                 "Ubicación",
        "project.site":                     "Obra",
        "project.building":                 "Edificio",
        "project.room":                     "Ambiente",
        "project.floor":                    "Número de piso",
        "project.notes":                    "Notas",
        "project.workType":                 "Tipo de trabajo",
        "project.unit":                     "Unidad",
        "project.targetThickness":          "Espesor objetivo",
        "project.tolerance":                "Tolerancia (±)",
        "project.recommended":              "Recomendado:",
        "project.deleteTitle":              "Eliminar Proyecto",
        "project.deleteConfirm":            "¿Eliminar este proyecto? Se eliminarán todos los escaneos e informes.",
        "project.deleteScansAndSave":       "Eliminar Escaneos y Guardar",
        "project.deleteScansTitle":         "¿Eliminar todos los datos de escaneo?",
        "project.deleteScansMessage":       "Guardar eliminará permanentemente todos los escaneos originales, reescaneos y resultados de análisis de espesor de este proyecto.",
        "project.deleteScansWarning":       "Guardar eliminará permanentemente %d escaneo(s) y todos los resultados de espesor.",
        // ── Project list ─────────────────────────────────────────────────────
        "projects.title":                   "Proyectos",
        "projects.search":                  "Buscar por nombre, cliente, obra, ingeniero",
        "projects.empty":                   "Sin proyectos aún",
        "projects.emptySearch":             "Sin proyectos coincidentes",
        // ── Project detail ────────────────────────────────────────────────────
        "detail.startOriginalScan":         "Iniciar Escaneo Original",
        "detail.newRescan":                 "Nuevo Reescaneo",
        "detail.reports":                   "Informes",
        "detail.colorPalette":              "Paleta de Colores",
        "detail.colorPalette.custom":       "Personalizado",
        "detail.timeline":                  "LÍNEA DE TIEMPO",
        "detail.desired":                   "Deseado",
        "detail.tolerance":                 "Tolerancia",
        "detail.tapToAnalyze":             "Tocar para analizar",
        "detail.vertices":                  "vértices",
        "detail.coverage":                  "cobertura",
        // ── Color palette editor ──────────────────────────────────────────────
        "palette.title":                    "Paleta de Colores",
        "palette.preview":                  "VISTA PREVIA DEL GRADIENTE",
        "palette.resetToDefault":           "Restaurar Predeterminado",
        "palette.bands":                    "bandas",
        // ── Reports ───────────────────────────────────────────────────────────
        "reports.title":                    "Informes",
        "reports.empty":                    "Sin informes aún",
        "reports.emptyNote":                "Genera uno desde la pantalla de Análisis después de calcular un mapa de espesor.",
        // ── Scan ──────────────────────────────────────────────────────────────
        "scan.finish":                      "Finalizar Escaneo",
        "scan.save":                        "Guardar Escaneo",
        "scan.label.optional":              "Etiqueta (opcional)",
        "scan.label.placeholder":           "p. ej. Escaneo Original",
        "scan.mesh":                        "Malla",
        "scan.anchors":                     "anclajes",
        "scan.coverage":                    "Cobertura",
        "scan.tracking.initializing":       "Mueve el dispositivo lentamente para comenzar el rastreo…",
        "scan.tracking.excessiveMotion":    "Moviéndose muy rápido — reduce la velocidad.",
        "scan.tracking.insufficientFeatures": "Apunta a una superficie con más textura.",
        "scan.tracking.relocalizing":       "Encontrando tu posición…",
        "scan.tracking.limited":            "El rastreo está limitado.",
        // ── Rescan ────────────────────────────────────────────────────────────
        "rescan.finish":                    "Finalizar Reescaneo",
        "rescan.save":                      "Guardar Reescaneo",
        "rescan.label.placeholder":         "p. ej. Después de la Segunda Capa",
        "rescan.colors":                    "Colores",
        "rescan.colors.active":             "Activo",
        "rescan.colors.ready":              "Listo",
        "rescan.colors.loading":            "Cargando",
        "rescan.heatmap":                   "Mapa de Calor",
        "rescan.heatmapActive":             "Mapa de Calor Activo",
        "rescan.cubicMeters":               "Metros Cúbicos",
        "rescan.calculating":               "Calculando…",
        "rescan.loadingMesh":               "Cargando malla…",
        "rescan.volume.plaster":            "Vol. Revoque",
        "rescan.volume.excavation":         "Vol. Excavación",
        // ── Analysis ──────────────────────────────────────────────────────────
        "analysis.title":                   "Análisis",
        "analysis.generateThicknessMap":    "Generar Mapa de Espesor",
        "analysis.thicknessMapNotGenerated": "Mapa de espesor no generado aún",
        "analysis.computing":               "Calculando…",
        "analysis.fullStatistics":          "Estadísticas completas",
        // ── Remote Control ────────────────────────────────────────────────────
        "remote.broadcasting":              "Transmitiendo",
        "remote.starting":                  "Iniciando…",
        "remote.joinRoom":                  "Unirse a Sala",
        "remote.broadcastScreen":           "Transmitir Pantalla",
        "remote.joinARoom":                 "Unirse a una Sala",
        "remote.stopBroadcasting":          "Detener Transmisión",
        "remote.stopBroadcastingQ":         "¿Detener transmisión?",
        "remote.title":                     "Control Remoto",
        "remote.peerToPeerTitle":           "Control Remoto Punto a Punto",
        "remote.peerToPeerSubtitle":        "Comparte tu pantalla y permite que otro dispositivo la controle — por WiFi o Bluetooth, sin necesidad de internet.",
        "remote.waitingForController":      "Esperando al controlador…",
        "remote.connectedControllers":      "CONTROLADORES CONECTADOS",
        "remote.waitingForDevice":          "Esperando que se conecte un dispositivo…",
        "remote.useAppFreely":              "Usa la app libremente",
        "remote.useAppFreelySubtitle":      "Navega a cualquier parte — el controlador ve la pantalla en la que estás y puede tocar para controlarla. Un indicador de transmisión permanece en la parte inferior de cada pantalla.",
        "remote.from":                      "Desde:",
        "remote.connectedTo":               "Conectado",
        "remote.searchingBroadcasters":     "Buscando transmisores…",
        "remote.noBroadcastersFound":       "No se encontraron transmisores",
        "remote.noBroadcastersNote":        "Abre Scan Art en el otro dispositivo, toca Control Remoto → Transmitir Pantalla y vuelve aquí.",
        "remote.availableRooms":            "SALAS DISPONIBLES",
        "remote.broadcasting.tapToConnect": "Transmitiendo · toca para conectar",
        "remote.waitingForStream":          "Esperando transmisión de pantalla…",
        "remote.keyboard":                  "Escribir y Enviar",
        "remote.keyboard.prompt":           "Escribe el texto para enviar al transmisor",
        "remote.keyboard.placeholder":      "Escribe aquí…",
        "remote.info.broadcastScreen.title": "Transmitir Pantalla",
        "remote.info.broadcastScreen.body": "Transmite tu pantalla a un controlador. Navega la app normalmente — el controlador ve todo lo que haces.",
        "remote.info.joinRoom.title":       "Unirse a una Sala",
        "remote.info.joinRoom.body":        "Se conecta a un transmisor, muestra su pantalla en vivo y envía tus toques para controlarlo.",
        "remote.info.wifi.title":           "WiFi o Bluetooth",
        "remote.info.wifi.body":            "Ambos dispositivos deben estar cerca. Funciona en la misma red local o Bluetooth directo — sin nube.",
        // ── Help ─────────────────────────────────────────────────────────────
        "help.title":                       "Ayuda",
        "help.1.title":                     "1. Crear un Proyecto",
        "help.1.text":                      "Establece el espesor de revoque deseado y la tolerancia para la pared que estás midiendo. Esto controla la leyenda de colores y las estadísticas de aprobado/reprobado.",
        "help.2.title":                     "2. Escaneo Original",
        "help.2.text":                      "Antes de revocar, escanea la pared sin revestimiento. Muévete lentamente y cubre toda el área, incluyendo parte del piso, techo o una puerta si es visible — estos ayudan a alinear futuros reescaneos.",
        "help.3.title":                     "3. Reescaneo Después del Revoque",
        "help.3.text":                      "Una vez aplicado el revoque, inicia un reescaneo. Scan Art intentará relocalizarse en la posición exacta del escaneo original — gira lentamente por el ambiente hasta que la alineación sea exitosa.",
        "help.4.title":                     "4. Generar Mapa de Espesor",
        "help.4.text":                      "En Análisis, toca Generar Mapa de Espesor. Scan Art compara ambos escaneos y colorea la pared según cuánto creció — el verde indica que está en el objetivo.",
        "help.5.title":                     "5. Exportar e Informe",
        "help.5.text":                      "Exporta la malla coloreada a DXF, OBJ, PLY, STL, USDZ, CSV o JSON, o genera un informe PDF para compartir con tu cliente o equipo.",
        "help.tips.title":                  "Consejos para Mejores Resultados",
        "help.tips.text":                   "Escanea con buena iluminación uniforme. Evita escanear superficies muy reflectantes o completamente lisas. Mantén el dispositivo moviéndose lentamente y de forma estable — los movimientos rápidos pueden perder el rastreo.",
        // ── About ────────────────────────────────────────────────────────────
        "about.title":                      "Acerca de",
        "about.subtitle":                   "Medición de espesor de revoque basada en LiDAR para ingenieros civiles, arquitectos y contratistas. Cada escaneo, medición e informe se queda en este dispositivo — Scan Art funciona completamente sin conexión.",
        "about.alignment":                  "Alineación",
        "about.alignment.value":            "Relocalización ARKit + refinamiento ICP",
        "about.measurement":                "Medición",
        "about.measurement.value":          "Muestreo de espesor por intersección rayo-malla",
        "about.storage":                    "Almacenamiento",
        "about.storage.value":              "100% en dispositivo, sin cuenta ni nube requerida",
        // ── Splash ───────────────────────────────────────────────────────────
        "splash.tagline":                   "Medición de Espesor de Revoque con LiDAR",
        "splash.unsupported":               "Este dispositivo no es compatible.",
        "splash.unsupportedNote":           "Scan Art requiere un escáner LiDAR, disponible en modelos iPhone Pro y iPad Pro.",
        // ── Export ───────────────────────────────────────────────────────────
        "export.generatePDF":               "Generar Informe PDF",
    ]
}
